
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vusumuzi
 */
public class AddStockPage extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddStockPage
     */
    public AddStockPage() {
        initComponents();
       int nunberOfLines=8;
       String[] productArray=new String[nunberOfLines];
       String[] requidArray=new String[nunberOfLines];
       String[] availableArray=new String[nunberOfLines];
       String[] dateArray=new String[nunberOfLines];
       String[] statusArray=new String[nunberOfLines];
       int count=0;
        
        
         try
        {
            File file=new File("StockData - Copy.txt");
            Scanner scan=new Scanner(file);
            scan.useDelimiter("\\s+");
           
      
           while(scan.hasNext())
            {
                String line1=scan.next();
                String line2=scan.next();
                String line3=scan.next();
                String line4=scan.next();
                String line5=scan.next();
               
                productArray[count]=line1;
                requidArray[count]=line2;
                availableArray[count]=line3;
                dateArray[count]=line4;
                statusArray[count]=line5;
                
                count++;     
            } 
       
           scan.close();
        }
        catch(Exception e)
        {}
        for(int i=0;i<count;i++)
        {
            String[] data={productArray[i+1],requidArray[i+1],availableArray[i+1],dateArray[i+1],statusArray[i+1]};
            DefaultTableModel model=(DefaultTableModel)table.getModel();
            model.addRow(data);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        productTxt = new javax.swing.JTextField();
        dateTxt = new javax.swing.JTextField();
        numOfStockTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addTxt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setClosable(true);
        setTitle("Add Stock Page");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT", "REQUIRED", "AVAILABLE", "DATE", "STATUS"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        productTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        productTxt.setForeground(new java.awt.Color(255, 0, 0));
        productTxt.setEnabled(false);
        productTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productTxtActionPerformed(evt);
            }
        });

        numOfStockTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numOfStockTxtActionPerformed(evt);
            }
        });

        jLabel1.setText("PRODUCT NAME       :");

        jLabel3.setText("DATE                         :");

        jLabel2.setText("NUMBER OF STOCK  :");

        addTxt.setText("ADD");
        addTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTxtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("ADD STOCK");

        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(productTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(dateTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(numOfStockTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(addTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addTxt)
                            .addComponent(numOfStockTxt)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(productTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numOfStockTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(43, 43, 43)
                .addComponent(addTxt)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productTxtActionPerformed
       int nunberOfLines=8;
       String[] productArray=new String[nunberOfLines];
       String[] requidArray=new String[nunberOfLines];
       String[] availableArray=new String[nunberOfLines];
       String[] dateArray=new String[nunberOfLines];
       String[] statusArray=new String[nunberOfLines];
         int count=0;     int clickedRow;
    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
       clickedRow=table.getSelectedRow();
      DefaultTableModel model=(DefaultTableModel)table.getModel();
      productTxt.setText(model.getValueAt(clickedRow, 0).toString());
      numOfStockTxt.setText(model.getValueAt(clickedRow, 2).toString());
      dateTxt.setText(model.getValueAt(clickedRow, 3).toString());
   
    }//GEN-LAST:event_tableMouseClicked
       double percentage;
      
    private void addTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTxtActionPerformed
       int i=table.getSelectedRow();
       DefaultTableModel model=(DefaultTableModel)table.getModel();
       if(i>=0)
       {  
           
           
           if ((!(numOfStockTxt.getText().isEmpty())) && ( !(numOfStockTxt.getText().isEmpty())))
           {
           String numStockHolder=numOfStockTxt.getText();
           int sumUpStock=Integer.parseInt(table.getValueAt(i, 2).toString())+Integer.parseInt(numStockHolder); //sumUpStock adds9i stock available with added stock
          
           model.setValueAt(sumUpStock, i, 2);
           
           model.setValueAt(dateTxt.getText(), i, 3);
           percentage=Integer.parseInt(table.getValueAt(i, 2).toString())/Integer.parseInt(table.getValueAt(i, 1).toString())*100;
           if (percentage>50)
                   {
                     model.setValueAt("Good", i, 4);  
                   }
           else if (percentage>=40)
                   {
                     model.setValueAt("Low", i, 4);  
                   }
            else
                   {
                     model.setValueAt("Too_Low", i, 4);  
                   }
           File file=new File("StockData - Copy.txt");
           try
           {
            
             FileWriter fWriter=new FileWriter(file);
             PrintWriter printer= new PrintWriter(new BufferedWriter(fWriter));
             
             for(int c=0;c<table.getColumnCount();c++)
             {
                printer.printf("%-24s",table.getColumnName(c));  
             }
              printer.println();
             for(int p=0;p< table.getRowCount();p++)
             {
                 for(int j=0;j<table.getColumnCount();j++)

                 {   
                     if (!(table.getModel().getValueAt(p, j)==(null)))
                             {
                                 printer.printf("%-24s",table.getModel().getValueAt(p, j));
                   
                             }
                   }
                   printer.println();
                  
             } 
             JOptionPane.showMessageDialog(null,"Stock added and updated on database");
             printer.close();
             fWriter.close();
           
         
           }
           catch (Exception e)
           {
              JOptionPane.showMessageDialog(null,"error occured while trying to write on the text file!");
           }
           
           }
           else
           {
              JOptionPane.showMessageDialog(null,"fill all spaces too add");  
           }
          
            
       }  
    }//GEN-LAST:event_addTxtActionPerformed

    private void numOfStockTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numOfStockTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numOfStockTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTxt;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numOfStockTxt;
    private javax.swing.JTextField productTxt;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
