 
import java.io.File;
import java.util.Scanner;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vusumuzi aka Vigie
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkbox1 = new java.awt.Checkbox();
        desktop1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        Login = new javax.swing.JButton();
        showPassTxt = new javax.swing.JCheckBox();
        regPage = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JPasswordField();

        checkbox1.setLabel("checkbox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        desktop1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOGIN", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 36), new java.awt.Color(102, 102, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("EMAIL            :");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("PASSWORD   :");

        jLabel3.setText("don't have an account yet ? ");

        emailTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });

        Login.setText("LOGIN");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        showPassTxt.setText(" show password");
        showPassTxt.setOpaque(false);
        showPassTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassTxtActionPerformed(evt);
            }
        });

        regPage.setBackground(new java.awt.Color(51, 51, 255));
        regPage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        regPage.setForeground(new java.awt.Color(51, 255, 51));
        regPage.setText("Click here!<<");
        regPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regPageMouseClicked(evt);
            }
        });

        passwordTxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        passwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtActionPerformed(evt);
            }
        });

        desktop1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop1.setLayer(emailTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop1.setLayer(Login, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop1.setLayer(showPassTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop1.setLayer(regPage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop1.setLayer(passwordTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktop1Layout = new javax.swing.GroupLayout(desktop1);
        desktop1.setLayout(desktop1Layout);
        desktop1Layout.setHorizontalGroup(
            desktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktop1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(desktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(55, 55, 55)
                .addGroup(desktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showPassTxt)
                    .addComponent(emailTxt)
                    .addComponent(Login)
                    .addGroup(desktop1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(regPage))
                    .addComponent(passwordTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        desktop1Layout.setVerticalGroup(
            desktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktop1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(desktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(desktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(showPassTxt)
                .addGap(32, 32, 32)
                .addComponent(Login)
                .addGap(18, 18, 18)
                .addGroup(desktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regPage))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        setSize(new java.awt.Dimension(593, 503));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  
    private void showPassTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassTxtActionPerformed
        if (showPassTxt.isSelected())
        {
            passwordTxt.setEchoChar((char)0);
        }
        else
        {
            passwordTxt.setEchoChar('*');  
        }
    }//GEN-LAST:event_showPassTxtActionPerformed

    private void passwordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxtActionPerformed

    private void regPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regPageMouseClicked
        Registration obj=new Registration();
        Login  objLogin=new Login();
        obj.setVisible(true);
         dispose();
        
    }//GEN-LAST:event_regPageMouseClicked
       String[] arrayNames= new String[500];
       String[] arrayEmail= new String[500];
       String[] arrayPass= new String[500];
       boolean found=false;
    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
       String email=emailTxt.getText().trim();
       String pass=passwordTxt.getText().trim();
      
       int count=0;
     
       if ((!(emailTxt.getText().isEmpty())) || (!(passwordTxt.getText().isEmpty()))) 
       {
        try
        {
           File file=new File("registrationData.txt");
           Scanner scan=new Scanner(file);
           scan.useDelimiter("[,\n]");
           
           while ((scan.hasNext()) && (found==false))
           {
               String line1=scan.next();
               String line2=scan.next();
               String line3=scan.next();
               arrayNames[count]=line1;
               arrayEmail[count]=line2;
               arrayPass[count]=line3;
           
          {
             if ((arrayEmail[count].trim().equals(email)) && (arrayPass[count].trim().equals(pass)))
              {
                found=true; 
               
              }
              count++; 
           } 
          
          
        }
            if (found)
           {
               JOptionPane.showMessageDialog(null,"access granted");
               HomePage_  objHome=new HomePage_();
               objHome.setVisible(true);
               dispose();
           } 
           else
           {
               JOptionPane.showMessageDialog(null,"access denaid wrong email or password!");
              
           }
            scan.close();
      }
      catch (Exception e)
        {
         JOptionPane.showMessageDialog(null,"error occured while trying to validate your credintials try again");   
        }
       }
       else
           {
             JOptionPane.showMessageDialog(null,"fill in on the fields");      
           }
   
    
    
    }//GEN-LAST:event_LoginActionPerformed

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private java.awt.Checkbox checkbox1;
    private javax.swing.JDesktopPane desktop1;
    public static javax.swing.JTextField emailTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JLabel regPage;
    private javax.swing.JCheckBox showPassTxt;
    // End of variables declaration//GEN-END:variables
}
