
import java.io.FileOutputStream;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import java.util.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vusumuzi
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        destop2 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JPasswordField();
        emailTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        confirmPassTxt = new javax.swing.JPasswordField();
        regist = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        destop2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRAION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 2, 36), new java.awt.Color(153, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("NAME                          :");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText(" E-MAIL                       :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("PASSWORD                 :  ");

        passwordTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtActionPerformed(evt);
            }
        });

        emailTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        nameTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("CONFIRM PASSWORD :");

        confirmPassTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPassTxtActionPerformed(evt);
            }
        });

        regist.setText("REGISTER");
        regist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registActionPerformed(evt);
            }
        });

        back.setText("back>>");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        destop2.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        destop2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        destop2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        destop2.setLayer(passwordTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        destop2.setLayer(emailTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        destop2.setLayer(nameTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        destop2.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        destop2.setLayer(confirmPassTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        destop2.setLayer(regist, javax.swing.JLayeredPane.DEFAULT_LAYER);
        destop2.setLayer(back, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout destop2Layout = new javax.swing.GroupLayout(destop2);
        destop2.setLayout(destop2Layout);
        destop2Layout.setHorizontalGroup(
            destop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(destop2Layout.createSequentialGroup()
                .addGroup(destop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(destop2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(destop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addGroup(destop2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(destop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addGroup(destop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(destop2Layout.createSequentialGroup()
                        .addComponent(regist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(back))
                    .addComponent(nameTxt)
                    .addComponent(emailTxt)
                    .addComponent(passwordTxt)
                    .addComponent(confirmPassTxt))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        destop2Layout.setVerticalGroup(
            destop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(destop2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(destop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(destop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(destop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(destop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(confirmPassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(destop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regist)
                    .addComponent(back))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(destop2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(destop2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        setSize(new java.awt.Dimension(558, 551));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxtActionPerformed

    private void confirmPassTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPassTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPassTxtActionPerformed

    private void registActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registActionPerformed
     String name=nameTxt.getText();
     String email=emailTxt.getText();
     String pass=passwordTxt.getText();
     String cPass=confirmPassTxt.getText();
     if ((!(emailTxt.getText().isEmpty())) || (!(passwordTxt.getText().isEmpty())) || (!(nameTxt.getText().isEmpty())) ||
             (!(passwordTxt.getText().isEmpty()))){
     
   {
       if(pass.equals(cPass))
       {
        
     try
     {
       FileOutputStream  file= new  FileOutputStream("registrationData.txt",true); 
       PrintWriter printer= new PrintWriter(file);
        
       printer.println(name+","+email+","+pass);
       printer.close();
       JOptionPane.showMessageDialog(null,"registration successfull login😃");
       Login objLogin=new Login();
      objLogin.setVisible(true);
      dispose();
       printer.close();
       setDefaultCloseOperation(DISPOSE_ON_CLOSE);
     }
     catch(Exception e)
     {
         JOptionPane.showMessageDialog(null,"arror occered 😢!");
     }
     
       }
         else
         {
           JOptionPane.showMessageDialog(null,"passwords are not the same!");  
         }
   }
  
  }
     else
     {
       JOptionPane.showMessageDialog(null,"fill in all the fields please!");
     }
    
        
    }//GEN-LAST:event_registActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       
        Login obj=new Login();
       obj.setVisible(true);
       dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JPasswordField confirmPassTxt;
    private javax.swing.JDesktopPane destop2;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JButton regist;
    // End of variables declaration//GEN-END:variables
}
