
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vusumuzi
 */
public class SellStockPage extends javax.swing.JInternalFrame {

    /**
     * Creates new form SellStockPage
     */
    public SellStockPage() {
        initComponents();
        int nunberOfLines=8;
       String[] productArray=new String[nunberOfLines];
       String[] requidArray=new String[nunberOfLines];
       String[] availableArray=new String[nunberOfLines];
       String[] dateArray=new String[nunberOfLines];
       String[] statusArray=new String[nunberOfLines];
      int count=0; 
      try
        {
            File file=new File("StockData - Copy.txt");
            Scanner scan=new Scanner(file);
            scan.useDelimiter("\\s+");
            while(scan.hasNext())
            {
                String line1=scan.next();
                String line2=scan.next();
                String line3=scan.next();
                String line4=scan.next();
                String line5=scan.next();
               
                productArray[count]=line1;
                requidArray[count]=line2;
                availableArray[count]=line3;
                dateArray[count]=line4;
                statusArray[count]=line5;

                count++;     
            }
            
            
         scan.close();
        }
        catch(Exception e)
        {
         JOptionPane.showMessageDialog(null,"an error occured!");
        }
        

        for(int i=0;i<count;i++)
        {
            String[] data={productArray[i+1],requidArray[i+1],availableArray[i+1],dateArray[i+1],statusArray[i+1]};
            DefaultTableModel model=(DefaultTableModel)table.getModel();
            model.addRow(data);
      
        }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        productTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numOfStockTxt = new javax.swing.JTextField();
        dateTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Sell Stock Page");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT", "REQUIRED", "AVAILABLE", "lDATE", "STATUS"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Sell Stock");

        productTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        productTxt.setEnabled(false);

        jLabel2.setText("PRODUCT NAME        :");

        jLabel3.setText("NUMBER OF STOCK   :");

        jLabel4.setText("DATE                          :");

        numOfStockTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numOfStockTxtActionPerformed(evt);
            }
        });

        dateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTxtActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("SELL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(productTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(numOfStockTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(dateTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel3))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))))
                        .addGap(59, 59, 59)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(productTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dateTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                            .addComponent(jButton1)
                            .addComponent(numOfStockTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(productTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(dateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(numOfStockTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addGap(32, 32, 32))
        );

        setBounds(0, 0, 699, 501);
    }// </editor-fold>//GEN-END:initComponents

    private void numOfStockTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numOfStockTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numOfStockTxtActionPerformed

    private void dateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTxtActionPerformed
      
    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
      int clickedRow;                                 
      clickedRow=table.getSelectedRow();
      DefaultTableModel model=(DefaultTableModel)table.getModel();
      productTxt.setText(model.getValueAt(clickedRow, 0).toString());
      numOfStockTxt.setText(model.getValueAt(clickedRow, 2).toString());
      dateTxt.setText(model.getValueAt(clickedRow, 3).toString());
    }//GEN-LAST:event_tableMouseClicked
    double percentage;
     File newTextFile=new File("StockDataHold.txt");
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         int i=table.getSelectedRow();
       DefaultTableModel model=(DefaultTableModel)table.getModel();
       if(i>=0)
       {   
            if ((!(numOfStockTxt.getText().isEmpty())) && (!(numOfStockTxt.getText().isEmpty())))
           {
           String numStockHolder=numOfStockTxt.getText();
           int sumUpStock=Integer.parseInt(table.getValueAt(i, 2).toString())-Integer.parseInt(numStockHolder); //sumUpStock minuses stock available with sold stock
          
           model.setValueAt(sumUpStock, i, 2);
           
           model.setValueAt(dateTxt.getText(), i, 3);
           percentage=Integer.parseInt(table.getValueAt(i, 2).toString())/Integer.parseInt(table.getValueAt(i, 1).toString())*100;
           if (percentage>50)
                   {
                     model.setValueAt("Good", i, 4);  
                   }
           else if (percentage>=40)
                   {
                     model.setValueAt("Low", i, 4);  
                   }
            else
                   {
                     model.setValueAt("Too_Low", i, 4);  
                   }
                 File file=new File("StockData - Copy.txt");
           try
           {
            
             FileWriter fWriter=new FileWriter(file );
             PrintWriter printer= new PrintWriter(new BufferedWriter(fWriter));
             
             for(int c=0;c<table.getColumnCount();c++)
             {
                printer.printf("%-24s",table.getColumnName(c));  
             }
              printer.println();
             for(int p=0;p< table.getRowCount();p++)
             {
                 for(int j=0;j<table.getColumnCount();j++)
                 {
                       if (!(table.getModel().getValueAt(p, j)==(null)))
                           {
                            printer.printf("%-24s",table.getModel().getValueAt(p, j));
                           }
                 }
                   printer.println();
                  
             } 
             JOptionPane.showMessageDialog(null,"Stock sold and database updated");
             printer.close();
             fWriter.close();
             
           }
           catch (Exception e)
           {
              JOptionPane.showMessageDialog(null,"error occured while trying to write on text file!");
           }
          
           }
            else
            {
              JOptionPane.showMessageDialog(null,"fill in all the spaces to Sell Stock");  
            }
            
            
          
       }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dateTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numOfStockTxt;
    private javax.swing.JTextField productTxt;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
